### ISSUE TITLE
Display validator name instead of id

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/block-metrics#27]
Please use the following mappings to display the validator name, rather than id, in the explorer:

`61B819A0BCF4E65AF8B6ED3AB287935074B8C7E3	Cosmostation`
`3B4F5C11663DC10A6D32403F945DED42AE1DD362	StakeWith.Us`
`8411B44F2FF2CE6A3143121EB5EEC1A23FCF2631	HashQuark`
`058078082E8ED2431EA61E69657BE27F0D7456FA	Node A Team`
`4A6CDCD260D1527CD1F89ECB5BA3A160FAB3B5F7	Forbole`
`A811EB8C0E76991BA241278886625CF081EFF874	01node.com`
`4C74A4E2156493E5FB329BE619C188519629CCE3	Bianjie`
`28BFE674AF17CFE4736C979CECFFC03A5490DE96	ChainLayer`
`DF97841F98E18B02F670C62830E13C40FFCE9D1E	syncnode`
`A5F88A83C831E6D84C83EED33870F4015D0FE94A	Stake Capital`

The validator set will not change for months so feel free to not be clever with the implementation, ie hard-code the values if you wish.

**Comment by orkunkl** [comment]
Moved to https://github.com/iov-one/quick-block-explorer/issues/7
