### ISSUE TITLE
Validate the correctness of the data 

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/block-metrics#8]
I just synced with hugnet to find some missed blocks, and got the following:

```
postgres=# select block_height, proposer_id, participant_ids from blocks where array_length(participant_ids, 1) != 4;
 block_height | proposer_id | participant_ids 
--------------+-------------+-----------------
            5 |           2 | {1,3,4}
           10 |           1 | {1,3,4}
           12 |           4 | {2,1,4}
           69 |           2 | {1,3,4}
        11443 |           3 | {1,3,4}
(5 rows)
```

Note that in 2 of the 5 examples, the proposer was not in the list of participants. Maybe there is some mis-match, like those participants are those who signed the block before or after??

**Comment by ruseinov** [comment]
I'm closing this as this seems to have been validated by multiple people already.
